Repository JudgmentLabs/judgeval, pull requests merged in 2025-04, with the labels that each got.

#154 Removing Process Example
  src/judgeval/data/__init__.py
  src/judgeval/data/api_example.py
  src/judgeval/data/result.py
  src/judgeval/scorers/score.py
  src/tests/data/test_api_example.py
  src/tests/data/test_result.py
  src/tests/scorers/test_score.py
Labels: In Review

#152 Fix: multiple client initialization issue
  src/judgeval/judgment_client.py
Labels: Ready for Review

#197 Added docs for MCP server
  docs/mcp_server/mcp_server.mdx
  docs/mint.json
Labels: In Review

#196 Automatic deep trace
  src/demo/simplified_tracing/example_complex_async.py
  src/e2etests/test_tracer.py
  src/judgeval/common/tracer.py
  src/tests/test_tracer_deep_tracing.py
Labels: In Review

#191 Doc Update for Async Eval
  docs/api_reference/judgment_client.mdx
  docs/evaluation/introduction.mdx
  docs/mint.json
Labels: In Review

#193 Added test for async LLM clients
  src/e2etests/test_tracer.py
Labels: In Review

#190 Sequence Updates
  docs/evaluation/data_datasets.mdx
  docs/evaluation/data_sequences.mdx
  docs/evaluation/introduction.mdx
  docs/evaluation/scorers/agent/derailment.mdx
  src/demo/dataset.py
  src/demo/demo.py
  src/demo/simple_trace.py
  src/e2etests/test_all_scorers.py
  src/e2etests/test_eval_operations.py
  src/e2etests/test_trace_operations.py
  src/judgeval/constants.py
  src/judgeval/data/datasets/dataset.py
  src/judgeval/data/datasets/eval_dataset_client.py
  src/judgeval/data/sequence.py
  src/judgeval/data/sequence_run.py
  src/judgeval/judgment_client.py
  src/judgeval/run_evaluation.py
Labels: Blocked, In Review

#198 Remove local scorers
  docs/api_reference/judgment_client.mdx
  src/e2etests/test_all_scorers.py
  src/e2etests/test_eval_operations.py
  src/judgeval/common/tracer.py
  src/judgeval/data/sequence.py
  src/judgeval/judgment_client.py
  src/judgeval/rules.py
  src/judgeval/run_evaluation.py
  src/judgeval/scorers/__init__.py
  src/judgeval/scorers/base_scorer.py
  src/judgeval/scorers/judgeval_scorers/__init__.py
  src/judgeval/scorers/judgeval_scorers/local_implementations/__init__.py
  src/judgeval/scorers/judgeval_scorers/local_implementations/answer_correctness/__init__.py
  src/judgeval/scorers/judgeval_scorers/local_implementations/answer_correctness/answer_correctness_scorer.py
  src/judgeval/scorers/judgeval_scorers/local_implementations/answer_correctness/prompts.py
  src/judgeval/scorers/judgeval_scorers/local_implementations/answer_relevancy/__init__.py
  src/judgeval/scorers/judgeval_scorers/local_implementations/answer_relevancy/answer_relevancy_scorer.py
  src/judgeval/scorers/judgeval_scorers/local_implementations/answer_relevancy/prompts.py
  src/judgeval/scorers/judgeval_scorers/local_implementations/comparison/__init__.py
  src/judgeval/scorers/judgeval_scorers/local_implementations/comparison/comparison_scorer.py
  src/judgeval/scorers/judgeval_scorers/local_implementations/comparison/prompts.py
  src/judgeval/scorers/judgeval_scorers/local_implementations/contextual_precision/__init__.py
  src/judgeval/scorers/judgeval_scorers/local_implementations/contextual_precision/contextual_precision_scorer.py
  src/judgeval/scorers/judgeval_scorers/local_implementations/contextual_precision/prompts.py
  src/judgeval/scorers/judgeval_scorers/local_implementations/contextual_recall/__init__.py
  src/judgeval/scorers/judgeval_scorers/local_implementations/contextual_recall/contextual_recall_scorer.py
  src/judgeval/scorers/judgeval_scorers/local_implementations/contextual_recall/prompts.py
  src/judgeval/scorers/judgeval_scorers/local_implementations/contextual_relevancy/__init__.py
  src/judgeval/scorers/judgeval_scorers/local_implementations/contextual_relevancy/contextual_relevancy_scorer.py
  src/judgeval/scorers/judgeval_scorers/local_implementations/contextual_relevancy/prompts.py
  src/judgeval/scorers/judgeval_scorers/local_implementations/execution_order/__init__.py
  src/judgeval/scorers/judgeval_scorers/local_implementations/execution_order/execution_order.py
  src/judgeval/scorers/judgeval_scorers/local_implementations/faithfulness/__init__.py
  src/judgeval/scorers/judgeval_scorers/local_implementations/faithfulness/faithfulness_scorer.py
  src/judgeval/scorers/judgeval_scorers/local_implementations/faithfulness/prompts.py
  src/judgeval/scorers/judgeval_scorers/local_implementations/hallucination/__init__.py
  src/judgeval/scorers/judgeval_scorers/local_implementations/hallucination/hallucination_scorer.py
  src/judgeval/scorers/judgeval_scorers/local_implementations/hallucination/prompts.py
  src/judgeval/scorers/judgeval_scorers/local_implementations/instruction_adherence/instruction_adherence.py
  src/judgeval/scorers/judgeval_scorers/local_implementations/instruction_adherence/prompt.py
  src/judgeval/scorers/judgeval_scorers/local_implementations/json_correctness/__init__.py
  src/judgeval/scorers/judgeval_scorers/local_implementations/json_correctness/json_correctness_scorer.py
  src/judgeval/scorers/judgeval_scorers/local_implementations/summarization/__init__.py
  src/judgeval/scorers/judgeval_scorers/local_implementations/summarization/prompts.py
  src/judgeval/scorers/judgeval_scorers/local_implementations/summarization/summarization_scorer.py
  src/tests/notification/test_notification_integration.py
  src/tests/notification/test_notification_unit.py
  src/tests/scorers/judgeval_scorers/test_answer_correctness.py
  src/tests/scorers/judgeval_scorers/test_answer_relevancy.py
  src/tests/scorers/judgeval_scorers/test_comparison.py
  src/tests/scorers/judgeval_scorers/test_contextual_precision.py
  src/tests/scorers/judgeval_scorers/test_contextual_recall.py
  src/tests/scorers/judgeval_scorers/test_contextual_relevancy.py
  src/tests/scorers/judgeval_scorers/test_execution_order.py
  src/tests/scorers/judgeval_scorers/test_faithfulness.py
  src/tests/scorers/judgeval_scorers/test_hallucination.py
  src/tests/scorers/judgeval_scorers/test_json_correctness.py
  src/tests/scorers/judgeval_scorers/test_summarization.py
  src/tests/scorers/judgeval_scorers/test_text2sql.py
Labels: Blocked, In Review

#204 Add Osiris Research section to the Scorers docs
  docs/evaluation/scorers/introduction.mdx
Labels: In Review

#177 Updated tracer
  docs/getting_started.mdx
  docs/monitoring/tracing.mdx
  src/demo/travel_agent.py
  src/e2etests/test_rules_alerts.py
  src/e2etests/test_tracer.py
  src/judgeval/common/tracer.py
  src/judgeval/run_evaluation.py
  src/judgeval/scorers/score.py
  src/tests/common/test_tracer.py
Labels: Blocked, In Review

#215 Fix docs. resotre original judgment.observe
  docs/api_reference/trace.mdx
  docs/getting_started.mdx
  docs/monitoring/tracing.mdx
Labels: In Review
